[package]
name = "StreamLock"
version = "1.0.0"
authors = ["StreamLock Team"]

[addresses]
streamlock = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-release-v1.18"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-release-v1.18"
subdir = "aptos-move/framework/aptos-stdlib"

[dev-dependencies]
